server:
  port: 8091

spring:
  application:
    name: eMart Euraka Service

eureka:
  instance:
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 45
  server:
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
         defaultZone: http://localhost:8091/eureka/
    